AUTO_ADD_GLOBAL_DEFINE_BY_NAME = MTK_SLC_BUFFER_SUPPORT MTK_LCM_DEVICE_TREE_SUPPORT MTK_BT_BLUEDROID_A2DP_APTX MTK_NVCONFIG_PARTITION_SUPPORT MTK_BT_BLUEDROID_HFP_AG_17 MTK_AURISYS_PHONE_CALL_SUPPORT MTK_HEADSET_ACTIVE_NOISE_CANCELLATION MTK_DYNAMIC_SBP_SUPPORT MTK_FACTORY_GAMMA_SUPPORT MTK_VT3G324M_SUPPORT MTK_WFC_SUPPORT MTK_BT_BLUEDROID_AVRCP_TG_15 MTK_BT_BLUEDROID_PLUS MTK_CAM_VSDOF_SUPPORT MTK_EXTERNAL_SIM_SUPPORT MTK_EFUSE_WRITER_SUPPORT MTK_FACTORY_MODE_IN_GB2312 MTK_A1_FEATURE MTK_HETCOMM_SUPPORT MTK_AUDIO_TUNNELING_SUPPORT CUSTOM_KERNEL_HEART_RATE_SENSOR CUSTOM_KERNEL_SENSORHUB CUSTOM_KERNEL_TILT_DETECTOR_SENSOR CUSTOM_KERNEL_IN_POCKET_SENSOR CUSTOM_KERNEL_WAKE_GESTURE_SENSOR CUSTOM_KERNEL_FACE_DOWN_SENSOR CUSTOM_KERNEL_PICK_UP_SENSOR CUSTOM_KERNEL_GLANCE_GESTURE_SENSOR CUSTOM_KERNEL_PEDOMETER CUSTOM_KERNEL_SHAKE_SENSOR CUSTOM_KERNEL_PEDOMETERENSOR CUSTOM_KERNEL_ACTIVITY_SENSOR CUSTOM_KERNEL_SIGNIFICANT_MOTION_SENSOR CUSTOM_KERNEL_STEP_COUNTER MTK_C2K_SUPPORT MTK_GMO_ROM_OPTIMIZE MTK_GMO_RAM_OPTIMIZE MTK_ENABLE_MD3 MTK_HEART_RATE_MONITOR_SUPPORT SENSOR_BATCH_SUPPORT MTK_MIRAVISION_IMAGE_DC_SUPPORT MTK_VOICE_INTERFACE_EXTENSION_SUPPORT MTK_LOSSLESS_BT_SUPPORT MTK_DTAG_DUAL_APN_SUPPORT MTK_DEINTERLACE_SUPPORT MTK_WIFI_MCC_SUPPORT TARGET_USES_LOGD MTK_EPDG_SUPPORT MTK_SUPPORT_TC1_TUNNING MTK_DUAL_INPUT_CHARGER_SUPPORT MTK_JEITA_STANDARD_SUPPORT MTK_AUDIO_ALAC_SUPPORT MTK_BQ24261_SUPPORT MTK_REGIONALPHONE_SUPPORT MTK_SENSOR_HUB_SUPPORT MTK_VIDEO_VP8ENC_SUPPORT LENOVO_X2 MTK_BQ24250_SUPPORT X2_BQ27531_SUPPORT X2_CHARGING_STANDARD_SUPPORT MTK_MAX77819_SUPPORT MTK_PCA9575A_SUPPORT MTK_MD_LOW_BAT_SUPPORT MTK_ALPS_BOX_TVE_SUPPORT MTK_EXTMD_NATIVE_DOWNLOAD_SUPPORT MTK_ALPS_BOX_DONGLE_SUPPORT MTK_ETHERNET_SUPPORT MTK_BESSURROUND_SUPPORT MTK_BOX_AUDIO_DDPLUS_SUPPORT MTK_PLAYBACK_60FPS_TO_30FPS MTK_SPEAKER_MONITOR_SUPPORT MTK_CAM_MMSDK_SUPPORT MTK_ANT_SUPPORT MTK_MIRAVISION_SETTING_SUPPORT MTK_PUMP_EXPRESS_SUPPORT MTK_BQ24157_SUPPORT MTK_MPEG_DASH_SUPPORT MTK_VOLTE_SUPPORT MTK_IMS_SUPPORT MTK_VOW_SUPPORT MTK_IPTV_SUPPORT MTK_PASSPOINT_R2_SUPPORT MTK_EXTERNAL_DONGLE_SUPPORT MTK_ALPS_BOX_SUPPORT MTK_OD_SUPPORT MTK_BQ24296_SUPPORT MTK_CAM_HDR_SUPPORT MTK_TC1_FEATURE MTK_BATTERY_PROTECT MTK_WIRELESS_CHARGER_SUPPORT MTK_CAM_STEREO_CAMERA_SUPPORT MTK_BESLOUDNESS_SUPPORT MTK_CAM_VHDR_SUPPORT MTK_CAM_EIS_SUPPORT MTK_CAM_VIDEO_FACEBEAUTY_SUPPORT MTK_CAM_FACEBEAUTY_SUPPORT MTK_WFD_SINK_UIBC_SUPPORT MTK_WFD_SINK_SUPPORT MTK_CAM_VSS_SUPPORT MTK_CAM_ZSD_SUPPORT MTK_POWER_EXT_DETECT MTK_CAM_LOMO_SUPPORT MTK_POST_PROCESS_FRAMEWORK_SUPPORT MTK_CAM_DEPTH_AF_SUPPORT MTK_MERGE_INTERFACE_SUPPORT MTK_CAM_NATIVE_PIP_SUPPORT MTK_CAM_NR3D_SUPPORT MTK_CAM_OT_SUPPORT MTK_CAM_SD_SUPPORT MTK_CAM_SINGLE_3DSHOT_SUPPORT MTK_CAM_AUTORAMA_SUPPORT MTK_CAM_IMAGE_REFOCUS_SUPPORT MTK_CAM_ASD_SUPPORT MTK_CAM_FD_SUPPORT MTK_CAM_GESTURE_SUPPORT MTK_MLC_NAND_SUPPORT MTK_FORCE_CLUSTER1 TRUSTONIC_TEE_SUPPORT MTK_SPI_NAND_SUPPORT MTK_RAWFS_NAND_SUPPORT MTK_PASSPOINT_R1_SUPPORT MTK_LOMO_SUPPORT MTK_EXTERNAL_LDO MTK_PMIC_MT6397 MTK_VOICE_CONTACT_SEARCH_SUPPORT MTK_TOUCH_BOOST MTK_SLOW_MOTION_VIDEO_SUPPORT MTK_VIDEO_HEVC_SUPPORT MTK_AUTO_DETECT_ALSPS MTK_GPT_SCHEME_SUPPORT MT6280_SUPER_DONGLE MTK_CSD_DIALER_SUPPORT MTK_PRIVACY_PROTECTION_LOCK MTK_SIM_RECOVERY MTK_FAN5402_SUPPORT MTK_AUDIO_HD_REC_SUPPORT MTK_PLAYREADY_SUPPORT MTK_AUDIO MTK_CLEARMOTION_SUPPORT MTK_FSCK_TUNE HW_HAVE_TP_THREAD MTK_NEW_COMBO_EMMC_SUPPORT MTK_PERSIST_PARTITION_SUPPORT MTK_DX_HDCP_SUPPORT MTK_COMBO_NAND_SUPPORT MTK_SMARTBOOK_SUPPORT MTK_DFO_RESOLUTION_SUPPORT MTK_HIGH_RESOLUTION_AUDIO_SUPPORT MTK_AUDIO_EXTCODEC_SUPPORT MTK_SUBTITLE_SUPPORT MTK_WIFIWPSP2P_NFC_SUPPORT MTK_SDIOAUTOK_SUPPORT MTK_MSDC1_NOT_SUPPORT_SDR104 MTK_FEMTO_CELL_SUPPORT MTK_CHIPTEST_INT MTK_USER_ROOT_SWITCH MTK_ENABLE_MD5 MTK_LTE_SUPPORT MTK_LTE_DC_SUPPORT MTK_WMV_PLAYBACK_SUPPORT MTK_WMA_PLAYBACK_SUPPORT MTK_MOBILE_MANAGEMENT MTK_PARTITION_TABLE_PLAIN_TEXT MTK_DOLBY_DAP_SUPPORT DOLBY_SUPPORT MTK_BQ24156_SUPPORT CUSTOM_KERNEL_BAROMETER MTK_BQ24158_SUPPORT MTK_TABLET_PLUGIN_BUILD MTK_WIFI_CALLING_RIL_SUPPORT MTK_MULTI_PARTITION_MOUNT_ONLY_SUPPORT MTK_BQ24297_SUPPORT MTK_3GDONGLE_SUPPORT MTK_PM_STATS_SUPPORT MTK_SWIP_WMAPRO MTK_AUDIO_DDPLUS_SUPPORT MTK_SEC_WFD_VIDEO_PATH_SUPPORT MTK_BATLOWV_NO_PANEL_ON_EARLY MTK_SIM_HOT_SWAP_COMMON_SLOT MTK_TER_SERVICE MTK_OWNER_SDCARD_ONLY_SUPPORT MTK_DRM_PLAYREADY_SUPPORT MTK_SHOW_MSENSOR_TOAST_SUPPORT MTK_AUDIO_CHANGE_SUPPORT MTK_VIBSPK_SUPPORT IS_VCORE_USE_6333VCORE IS_VRF18_USE_6333VRF18 IS_VM_USE_6333VM MTK_VIDEO_AUTO_FLASH_SUPPORT MTK_AIV_SUPPORT MTK_WFD_HDCP_TX_SUPPORT PURE_AP_USE_EXTERNAL_MODEM MTK_NO_NEED_USB_LED MTK_HDMI_HDCP_SUPPORT MTK_INTERNAL_HDMI_SUPPORT MTK_INTERNAL_MHL_SUPPORT MTK_DMNR_TUNING_AT_MD NAND_OTP_SUPPORT MTK_DVFS_DISABLE_LOW_VOLTAGE_SUPPORT MTK_VOIP_ENHANCEMENT_SUPPORT MTK_HANDSFREE_DMNR_SUPPORT MTK_SWCHR_SUPPORT MTK_MT6333_SUPPORT MTK_MULTISIM_RINGTONE_SUPPORT MTK_DRM_KEY_MNG_SUPPORT MTK_SEC_VIDEO_PATH_SUPPORT MTK_WVDRM_L1_SUPPORT MTK_IN_HOUSE_TEE_SUPPORT MTK_DISABLE_POWER_ON_OFF_VOLTAGE_LIMITATION MTK_CTA_SUPPORT MTK_DFO_SUPPORT HAVE_MATV_FEATURE MTK_MATV_SERIAL_IF_SUPPORT MTK_BIP_SCWS MTK_MDM_FUMO MTK_MDM_LAWMO MTK_MDM_SCOMO TELEPHONY_DFOSET MTK_UART_USB_SWITCH MTK_FAT_ON_NAND MTK_AUDIO_RAW_SUPPORT MTK_MD_SHUT_DOWN_NT MTK_CACHE_MERGE_SUPPORT MTK_IPV6_TETHER_PD_MODE MTK_UMTS_TDD128_MODE MTK_YMAL_SCATTER_FILE_SUPPORT MTK_RADIOOFF_POWER_OFF_MD MTK_MT8193_HDCP_SUPPORT MTK_LCEEFT_SUPPORT MTK_PLATFORM_OPTIMIZE MTK_HW_ENHANCE MTK_PQ_SUPPORT MTK_AUDIO_ADPCM_SUPPORT HAVE_ADPCMENCODE_FEATURE MTK_2IN1_SPK_SUPPORT MTK_WEB_NOTIFICATION_SUPPORT MTK_GEMINI_4SIM_SUPPORT MTK_GEMINI_3SIM_SUPPORT MTK_VOICE_UNLOCK_SUPPORT MTK_VOICE_UI_SUPPORT MTK_BEAM_PLUS_SUPPORT MTK_IPOH_SUPPORT MTK_BQ27541_SUPPORT MTK_WFD_SUPPORT MTK_IPV6_TETHER_NDP_MODE MTK_TETHERING_EEM_SUPPORT MTK_AAL_SUPPORT MTK_KERNEL_POWER_OFF_CHARGING MTK_FLIGHT_MODE_POWER_OFF_MD MTK_ENABLE_MD1 MTK_ENABLE_MD2 MTK_ACMT_DEBUG MTK_BT_PROFILE_AVRCP MTK_MMPROFILE_SUPPORT MTK_GPS_SUPPORT MTK_MULTIBRIDGE_SUPPORT EVDO_DT_SUPPORT MTK_CAMCORDER_PROFILE_MID_MP4 MTK_FM_SUPPORT MTK_TABLET_PLATFORM MTK_AUTO_DETECT_MAGNETOMETER MTK_NCP1851_SUPPORT MTK_FM_RECORDING_SUPPORT MTK_DEDICATEDAPN_SUPPORT MTK_DT_SUPPORT MTK_NFC_SUPPORT MTK_MASS_STORAGE MTK_BICR_SUPPORT MTK_COMBO_QUICK_SLEEP_SUPPORT MTK_MT8193_SUPPORT HAVE_AACENCODE_FEATURE MTK_FM_50KHZ_SUPPORT MTK_COMBO_SUPPORT MTK_2SDCARD_SWAP CUSTOM_KERNEL_GYROSCOPE MTK_SHARED_SDCARD MTK_EMMC_DISCARD MTK_DSPIRDBG MTK_MULTI_STORAGE_SUPPORT CUSTOM_KERNEL_ALSPS MTK_ENABLE_VIDEO_EDITOR CUSTOM_KERNEL_ACCELEROMETER MTK_DUAL_MIC_SUPPORT MTK_WAPI_SUPPORT MTK_FD_SUPPORT MTK_DISPLAY_HIGH_RESOLUTION MTK_BT_SUPPORT MTK_TABLET_DRAM MTK_FACEBEAUTY_SUPPORT EVDO_DT_VIA_SUPPORT MTK_FAN5405_SUPPORT MTK_BQ24160_SUPPORT MTK_ASF_PLAYBACK_SUPPORT MTK_HIGH_QUALITY_THUMBNAIL MTK_SPH_EHN_CTRL_SUPPORT MTK_FM_TX_SUPPORT MTK_BRAZIL_CUSTOMIZATION_VIVO MTK_BRAZIL_CUSTOMIZATION_CLARO HAVE_XLOG_FEATURE MTK_IPV6_SUPPORT MTK_AUTORAMA_SUPPORT MTK_EAP_SIM_AKA MTK_MATV_ANALOG_SUPPORT MTK_BSP_PACKAGE MTK_BRAZIL_CUSTOMIZATION MTK_NVRAM_SECURITY CUSTOM_KERNEL_MAGNETOMETER MTK_CAMERA_APP_3DHW_SUPPORT MTK_WLANBT_SINGLEANT MTK_WLAN_SUPPORT MTK_TETHERINGIPV6_SUPPORT MTK_AUTO_DETECT_ACCELEROMETER HAVE_CMMB_FEATURE MTK_MT8193_HDMI_SUPPORT MTK_EMMC_SUPPORT_OTP MTK_TB_APP_CALL_FORCE_SPEAKER_ON MTK_PRODUCT_INFO_SUPPORT MTK_FM_SHORT_ANTENNA_SUPPORT MTK_HDMI_SUPPORT MTK_M4U_SUPPORT MTK_MT8193_NFI_SUPPORT MTK_ION_SUPPORT MTK_FSCK_MSDOS_MTK HAVE_AWBENCODE_FEATURE MTK_BQ24196_SUPPORT MTK_CAMERA_BSP_SUPPORT MTK_FM_RX_SUPPORT MTK_WB_SPEECH_SUPPORT ENCRY_PARTITION_SUPPORT MTK_SD_REINIT_SUPPORT MTK_SENSOR_SUPPORT MTK_EMMC_SUPPORT MTK_COMBO_CORE_DUMP_SUPPORT MTK_DHCPV6C_WIFI MTK_EMULATOR_SUPPORT MTK_NAND_UBIFS_SUPPORT MTK_YAML_SCATTER_FILE_SUPPORT MTK_CTPPPOE_SUPPORT MTK_WORLD_PHONE MTK_VIDEO_VP9_SUPPORT MTK_THERMAL_PA_VIA_ATCMD MTK_FLV_PLAYBACK_SUPPORT MTK_AUDIO_APE_SUPPORT MTK_AVI_PLAYBACK_SUPPORT USE_FRAUNHOFER_AAC MTK_DRM_APP MTK_OGM_PLAYBACK_SUPPORT MTK_MTKPS_PLAYBACK_SUPPORT MTK_MT6306_SUPPORT  LENOVO_RECOVERY_SUPPORT LENOVO_POWEROFF_CHARGING_UI MTK_BQ24296_SUPPORT LENOVO_SHOW_UI_IN_BAT_OVERDISCHARGE_SUPPORT LENOVO_SHOW_LOW_BAT_UI_IN_LK_SUPPORT MAX17058_SUPPORT LENOVO_AIO_PQ_MULTI MTK_NCP1854_SUPPORT  LENOVO_AIO_ROW_PQ_MULTI
AUTO_ADD_GLOBAL_DEFINE_BY_NAME_VALUE = MTK_TLC_SLC_RATIO MAXIM_SPEAKER_SUPPORT MTK_VZW_CHIPTEST_MODE_SUPPORT MTK_CAM_ZSDHDR_SUPPORT MTK_CAM_ZSDMFB_SUPPORT MTK_AUDIO_MIC_INVERSE MTK_HAC_SUPPORT SIM_ME_LOCK_MODE CUSTOM_CONFIG_MAX_DRAM_SIZE MTK_MAGICONFERENCE_SUPPORT MTK_IDC_SUPPORT MTK_MD_SBP_CUSTOM_VALUE MTK_ANTIBRICKING_LEVEL MTK_CAM_MFB_SUPPORT MTK_CAM_CONTINUOUS_SHOT_MODE MTK_ICUSB_SUPPORT MTK_FW_UPGRADE_APP MTK_FW_UPGRADE MTK_VIDEO_4KH264_SUPPORT MTK_HOTKNOT_SUPPORT MTK_TELEPHONY_BOOTUP_MODE_SLOT2 MTK_TELEPHONY_BOOTUP_MODE_SLOT1 MTK_NFC_SE_NUM MTK_OVERLAY_ENGINE_SUPPORT MTK_PCB_BATTERY_SENSOR MTK_SIM1_SOCKET_TYPE MTK_SIM2_SOCKET_TYPE CUSTOM_KERNEL_MAIN2_IMGSENSOR CUSTOM_KERNEL_SSW MTK_LCM_PHYSICAL_ROTATION LCM_WIDTH MTK_SHARE_MODEM_SUPPORT MTK_SINGLE_3DSHOT_SUPPORT MTK_EXTERNAL_MODEM_SLOT MTK_NEON_SUPPORT MTK_SHARE_MODEM_CURRENT LCM_HEIGHT MTK_NTFS_OPENSOURCE_SUPPORT LENOVO_PIEZO_SPEAKER_SUPPORT
AUTO_ADD_GLOBAL_DEFINE_BY_VALUE = BOOT_LOGO MTK_AUDIO_BLOUD_CUSTOMPARAMETER_REV MTK_PLATFORM CUSTOM_HAL_LENS CUSTOM_KERNEL_LENS CUSTOM_KERNEL_MAIN_BACKUP_LENS MTK_MODEM_SUPPORT MTK_ATV_CHIP CUSTOM_KERNEL_MAIN_IMGSENSOR MTK_BT_CHIP MTK_WLAN_CHIP CUSTOM_KERNEL_SUB_BACKUP_IMGSENSOR CUSTOM_KERNEL_MAIN_BACKUP_IMGSENSOR CUSTOM_KERNEL_FLASHLIGHT CUSTOM_KERNEL_SUB_IMGSENSOR CUSTOM_KERNEL_SUB_LENS CUSTOM_KERNEL_IMGSENSOR MTK_FM_RX_AUDIO MTK_COMBO_CHIP MTK_GPS_CHIP CUSTOM_KERNEL_SUB_BACKUP_LENS CUSTOM_KERNEL_MAIN_LENS MTK_FM_TX_AUDIO MTK_FM_CHIP CUSTOM_KERNEL_MAIN2_IMGSENSOR BOOT_LOGO
BOOT_LOGO = hd720
BUILD_KERNEL = yes
BUILD_LK = yes
BUILD_MD32 = yes
BUILD_MTK_SDK =
BUILD_PRELOADER = yes
BUILD_UBOOT = no
CUSTOM_BUILD_VERNO =
CUSTOM_CONFIG_MAX_DRAM_SIZE = 0x100000000
CUSTOM_HAL_ANT = mt6752_ant_m1
CUSTOM_HAL_AUDIOFLINGER = audio
CUSTOM_HAL_BLUETOOTH = bluetooth
CUSTOM_HAL_CAMERA = camera

CUSTOM_HAL_COMBO = mt6752
CUSTOM_HAL_EEPROM = dummy_eeprom
 #lenovo-sw wush1 add  begin

CUSTOM_HAL_CAM_CAL = dummy_eeprom
CUSTOM_HAL_FLASHLIGHT = dummy_flashlight
CUSTOM_HAL_IMGSENSOR = imx219ofilm_mipi_raw hi551qtech_mipi_raw hi551qtechv2_mipi_raw
CUSTOM_HAL_LENS = dw9718ofilmaf sensordrive dummy_lens
CUSTOM_HAL_MAIN2_IMGSENSOR =

CUSTOM_HAL_MAIN_IMGSENSOR = imx219ofilm_mipi_raw
CUSTOM_HAL_MAIN_LENS = dw9718ofilmaf

CUSTOM_HAL_MAIN_BACKUP_IMGSENSOR =
CUSTOM_HAL_MAIN_BACKUP_LENS =


CUSTOM_HAL_SUB_IMGSENSOR = hi551qtech_mipi_raw
CUSTOM_HAL_SUB_LENS =


CUSTOM_HAL_SUB_BACKUP_IMGSENSOR = hi551qtechv2_mipi_raw
CUSTOM_HAL_SUB_BACKUP_LENS =


CUSTOM_KERNEL_IMGSENSOR = imx219ofilm_mipi_raw hi551qtech_mipi_raw hi551qtechv2_mipi_raw

CUSTOM_KERNEL_LENS = dw9718ofilmaf sensordrive dummy_lens

CUSTOM_KERNEL_MAIN_IMGSENSOR = imx219ofilm_mipi_raw
CUSTOM_KERNEL_MAIN_LENS = dw9718ofilmaf

CUSTOM_KERNEL_MAIN_BACKUP_IMGSENSOR =
CUSTOM_KERNEL_MAIN_BACKUP_LENS =

CUSTOM_KERNEL_MAIN2_BACKUP_IMGSENSOR = 
CUSTOM_KERNEL_MAIN2_IMGSENSOR =

CUSTOM_KERNEL_SUB_IMGSENSOR = hi551qtech_mipi_raw
CUSTOM_KERNEL_SUB_LENS =

CUSTOM_KERNEL_SUB_BACKUP_IMGSENSOR = hi551qtechv2_mipi_raw
CUSTOM_KERNEL_SUB_BACKUP_LENS =


#lenovo.sw end wush1 end

CUSTOM_HAL_MSENSORLIB = mmc328x akm8975 ami304 yamaha530 mag3110 akmd8963 bmm050 mc6420 mmc3416x s62xd lsm303md hscdtd006 qmc5983 akmd09911 mc64xx bmm056 mc41xx
CUSTOM_HAL_SENSORS = sensor

#lenovo-sw molg1 add begin
CUSTOM_KERNEL_ACCELEROMETER = bma222E-aio
CUSTOM_KERNEL_ACTIVITY_SENSOR = no
CUSTOM_KERNEL_ALSPS = EPL21822-aio
CUSTOM_KERNEL_BAROMETER =
CUSTOM_KERNEL_BATTERY = battery
CUSTOM_KERNEL_CAMERA = camera
CUSTOM_KERNEL_CAM_CAL = dummy_eeprom
CUSTOM_KERNEL_CORE = src
CUSTOM_KERNEL_DCT = dct
CUSTOM_KERNEL_EEPROM = dummy_eeprom
CUSTOM_KERNEL_FACE_DOWN_SENSOR =no
CUSTOM_KERNEL_FLASHLIGHT = constant_flashlight
CUSTOM_KERNEL_GYROSCOPE =
#lenovo-sw molg1 add end
CUSTOM_KERNEL_HEADSET = accdet

CUSTOM_KERNEL_KPD = kpd
CUSTOM_KERNEL_LEDS = mt65xx

CUSTOM_KERNEL_MAGNETOMETER = akm09911-aio

#lenovo-sw molg1 add begin
CUSTOM_KERNEL_PEDOMETER = no
CUSTOM_KERNEL_PICK_UP_SENSOR = no
CUSTOM_KERNEL_RTC = rtc
CUSTOM_KERNEL_SENSORHUB = no
CUSTOM_KERNEL_SHAKE_SENSOR = no
CUSTOM_KERNEL_SIGNIFICANT_MOTION_SENSOR = no
#wangwy6 aio_5m_m bring up 20151111 start
#CUSTOM_KERNEL_SOUND = amp_6323pmic_spk
CUSTOM_KERNEL_SOUND = 
#wangwy6 aio_5m_m bring up 20151111 end
CUSTOM_KERNEL_SSW = ssw_generic_v2
CUSTOM_KERNEL_STEP_COUNTER = no
#lenovo-sw molg1 add end

CUSTOM_KERNEL_TOUCHPANEL = GT9XX_hotknot
CUSTOM_KERNEL_USB = mt6577
CUSTOM_KERNEL_VIBRATOR = vibrator
CUSTOM_MODEM = aio_row_lwg_dsds
CUSTOM_SEC_AUTH_SUPPORT = no
CUSTOM_SEC_SIGNTOOL_SUPPORT = no
DCORE_TEST_MODE1 = no
DEFAULT_INPUT_METHOD = com.cooted.smartinputv5.TouchPalIME
DEFAULT_LATIN_IME_LANGUAGES = en-US fr ru
DISABLE_EARPIECE = no
ENCRY_PARTITION_SUPPORT = no
EVB = yes
EVDO_DT_SUPPORT = no
EVDO_DT_VIA_SUPPORT = no
EVDO_IR_SUPPORT = no
FEATURE_FTM_AUDIO_AUTOTEST = yes
FEATURE_FTM_AUDIO_TEST = yes
FPGA_EARLY_PORTING = no
GEMINI = yes
GOOGLE_RELEASE_RIL = no
HAVE_AACENCODE_FEATURE = yes
HAVE_ADPCMENCODE_FEATURE = yes
HAVE_AEE_FEATURE = yes
HAVE_APPC_FEATURE = no
HAVE_AWBENCODE_FEATURE = yes
HAVE_MATV_FEATURE = no
HAVE_SRSAUDIOEFFECT_FEATURE = no
HAVE_VORBISENC_FEATURE = yes
HAVE_XLOG_FEATURE = yes
HW_HAVE_TP_THREAD = no
IS_VCORE_USE_6333VCORE = no
IS_VM_USE_6333VM = no
IS_VRF18_USE_6333VRF18 = no
KBUILD_OUTPUT_SUPPORT = yes
LCM_FAKE_HEIGHT = 0
LCM_FAKE_WIDTH = 0
LCM_HEIGHT = 1280
LCM_WIDTH = 720
LEGACY_DFO_GEN = no
LINUX_KERNEL_VERSION = kernel-3.10
MAXIM_SPEAKER_SUPPORT = no
MD32_TOOLCHAIN_MODULE = IPDesigner/12R2.36-64
MD5_SIZE = 0x01600000
MD5_SMEM_SIZE = 0x00200000
MICROTRUST_TEE_SUPPORT = no
MT6280_SUPER_DONGLE = no
MTK_2IN1_SPK_SUPPORT = no
MTK_2SDCARD_SWAP = no
MTK_3GDONGLE_SUPPORT = no
MTK_AAL_SUPPORT = no
MTK_ACMT_DEBUG = no
MTK_ACWFDIALOG_APP = yes
MTK_AGPS_APP = yes
MTK_AIV_SUPPORT = no
MTK_ALPS_BOX_DONGLE_SUPPORT = no
MTK_ALPS_BOX_SUPPORT = no
MTK_ALPS_BOX_TVE_SUPPORT = no
MTK_ANDROIDFACTORYMODE_APP = yes
MTK_ANDROID_FOR_WORK_SUPPORT = yes
MTK_ANTIBRICKING_LEVEL = 2
MTK_ANT_SUPPORT = no
MTK_API_CHECK = yes
MTK_APKINSTALLER_APP = no
MTK_APPENDED_DTB_SUPPORT = yes
MTK_APP_GUIDE = yes
MTK_AP_SPEECH_ENHANCEMENT = no
MTK_ASD_SUPPORT = yes
MTK_ASR_SUPPORT = no
MTK_ATF_SUPPORT = yes
MTK_ATV_CHIP =
#lenovo-sw.lily8.disable mtk audio enhancement.2015-10-13
MTK_AUDENH_SUPPORT = no
#lenovo-sw.lily8.disable mtk audio enhancement.2015-10-13
MTK_AUDIO = yes
MTK_AUDIO_ADPCM_SUPPORT = yes
MTK_AUDIO_ALAC_SUPPORT = yes
MTK_AUDIO_APE_SUPPORT = yes
MTK_AUDIO_BLOUD_CUSTOMPARAMETER_REV = MTK_AUDIO_BLOUD_CUSTOMPARAMETER_V5
MTK_AUDIO_CHANGE_SUPPORT = no
MTK_AUDIO_DDPLUS_SUPPORT = yes
MTK_AUDIO_EXTCODEC_SUPPORT = no
MTK_AUDIO_GAIN_TABLE_SUPPORT = no
MTK_AUDIO_HD_REC_SUPPORT = yes
MTK_AUDIO_MIC_INVERSE = no
MTK_AUDIO_PROFILES = no
MTK_AUDIO_RAW_SUPPORT = yes
MTK_AUDIO_TUNNELING_SUPPORT = no
MTK_AUIDO_MIC_INVERSE = no
MTK_AURISYS_PHONE_CALL_SUPPORT = no
MTK_AUTOIP_SUPPORT = no
MTK_AUTORAMA_SUPPORT = yes
MTK_AUTO_DETECT_ACCELEROMETER = no
MTK_AUTO_DETECT_ALSPS = no
MTK_AUTO_DETECT_MAGNETOMETER = no
MTK_AUTO_SANITY = no
MTK_AVI_PLAYBACK_SUPPORT = yes
MTK_BATLOWV_NO_PANEL_ON_EARLY = no
MTK_BATTERY_PROTECT = no
MTK_BEAM_PLUS_SUPPORT = no
#wangwy6 for aio_5m_m bring up 20151111 start
MTK_BESLOUDNESS_SUPPORT = no
MTK_BESSURROUND_SUPPORT = no
#wangwy6 for aio_5m_m bring up 20151111 end
MTK_BG_POWER_SAVING_SUPPORT = yes
MTK_BG_POWER_SAVING_UI_SUPPORT = yes
MTK_BICR_SUPPORT = yes
MTK_BIP_SCWS = yes
MTK_BOX_AUDIO_DDPLUS_SUPPORT = no
MTK_BQ24156_SUPPORT = no
MTK_BQ24157_SUPPORT = yes
MTK_BQ24158_SUPPORT = no
MTK_BQ24160_SUPPORT = no
MTK_BQ24261_SUPPORT = no
MTK_BQ24296_SUPPORT = no
MTK_BQ24297_SUPPORT = no
MTK_BQ27541_SUPPORT = no
MTK_BRANCH = alps-mp-m0.mp1
MTK_BRAZIL_CUSTOMIZATION = no
MTK_BRAZIL_CUSTOMIZATION_CLARO = no
MTK_BRAZIL_CUSTOMIZATION_TIM = no
MTK_BRAZIL_CUSTOMIZATION_VIVO = no
MTK_BSP_PACKAGE = no
MTK_BT_BLE_MANAGER_SUPPORT = no
MTK_BT_BLUEDROID_A2DP_APTX = no
MTK_BT_BLUEDROID_AVRCP_TG_15 = no
MTK_BT_BLUEDROID_HFP_AG_17 = yes
MTK_BT_BLUEDROID_PLUS = yes
MTK_BT_CHIP = MTK_CONSYS_MT6752
MTK_BT_SUPPORT = yes
MTK_BUFFER_COMPRESSION_SUPPORT = no
MTK_BUILD_VERNO = alps-mp-m0.mp1-V2.39_lenovo6752.65.m_P10
MTK_BWC_SUPPORT = yes
MTK_C2K_DATA_PPP_SUPPORT = no
MTK_C2K_SUPPORT = no
MTK_CACHE_MERGE_SUPPORT = no
MTK_CALENDAR_IMPORTER_APP = yes
MTK_CAMCORDER_PROFILE_MID_MP4 = no
MTK_CAMERA_APP = no
MTK_CAMERA_APP_3DHW_SUPPORT = yes
MTK_CAMERA_BSP_SUPPORT = yes
MTK_CAMERA_OT_SUPPORT = no
MTK_CAM_ASD_SUPPORT = yes
MTK_CAM_AUTORAMA_SUPPORT = yes
MTK_CAM_CONTINUOUS_SHOT_MODE = 1
MTK_CAM_DEPTH_AF_SUPPORT = no
# lenovo.sw START wangsx3 disable EIS on AIO,due to dummy gyro
MTK_CAM_EIS_SUPPORT = no
# lenovo.sw END wangsx3 disable EIS on AIO,due to dummy gyro
MTK_CAM_FACEBEAUTY_SUPPORT = yes
MTK_CAM_FD_SUPPORT = yes
MTK_CAM_GESTURE_SUPPORT = yes
MTK_CAM_HDR_SUPPORT = yes
MTK_CAM_IMAGE_REFOCUS_SUPPORT = NONE
MTK_CAM_LOMO_SUPPORT = yes
MTK_CAM_MFB_SUPPORT = 3
MTK_CAM_MMSDK_SUPPORT = no
MTK_CAM_NATIVE_PIP_SUPPORT = yes
MTK_CAM_NR3D_SUPPORT = yes
MTK_CAM_OT_SUPPORT = yes
MTK_CAM_SD_SUPPORT = yes
MTK_CAM_SINGLE_3DSHOT_SUPPORT = no
MTK_CAM_STEREO_CAMERA_SUPPORT = no
MTK_CAM_VHDR_SUPPORT = yes
MTK_CAM_VIDEO_FACEBEAUTY_SUPPORT = yes
MTK_CAM_VSDOF_SUPPORT = no
MTK_CAM_VSS_SUPPORT = yes
MTK_CAM_ZSDHDR_SUPPORT = no
MTK_CAM_ZSDMFB_SUPPORT = no
MTK_CAM_ZSD_SUPPORT = yes
MTK_CC33_SUPPORT = no
MTK_CDS_EM_SUPPORT = yes
MTK_CHARM_SUPPORT = no
MTK_CHIPTEST_INT = no
MTK_CHIP_VER = S01
MTK_CHKIMGSIZE_SUPPORT = yes
MTK_CIP_SUPPORT = no
MTK_CLEARMOTION_SUPPORT = no
MTK_CMAS_SUPPORT = no
MTK_CMCC_FT_PRECHECK_SUPPORT = yes
MTK_CMCC_RCS_QRCODE_SUPPORT = no
MTK_COMBO_CHIP = CONSYS_6752
MTK_COMBO_NAND_SUPPORT = no
MTK_COMBO_SUPPORT = yes
MTK_CPU = arm_cortexa7
MTK_CSD_DIALER_SUPPORT = no
MTK_CTA_SET = no
MTK_CTA_SUPPORT = no
MTK_CTPPPOE_SUPPORT = no
MTK_CTSC_MTBF_INTERNAL_SUPPORT = no
MTK_CUSTOMERSERVICE_APP = no
MTK_DAL_SUPPORT = no
MTK_DATADIALOG_APP = no

#lenovo-sw shenying2 AIOARIESM-530
MTK_DATA_TRANSFER_APP = no
MTK_DEDICATEDAPN_SUPPORT = no
MTK_DEFAULT_DATA_OFF = no
MTK_DEINTERLACE_SUPPORT = yes
MTK_DENA_MINIROSANGUO_APP = no
MTK_DENA_MOBAGE_APP = no
MTK_DEVREG_APP = no
MTK_DFO_RESOLUTION_SUPPORT = no
MTK_DHCPV6C_WIFI = yes
MTK_DIALER_SEARCH_SUPPORT = yes
MTK_DIGITAL_MIC_SUPPORT = no
#Lenovo-sw lixp5 modify 2015-10-13 begin, enable sim switch
#MTK_DISABLE_CAPABILITY_SWITCH = yes
MTK_DISABLE_CAPABILITY_SWITCH = no
#Lenovo-sw lixp5 modify 2015-10-13 end
MTK_DISABLE_EFUSE = no
MTK_DISABLE_POWER_ON_OFF_VOLTAGE_LIMITATION = no
MTK_DISPLAY_120HZ_SUPPORT = no
MTK_DISPLAY_HIGH_RESOLUTION = no
MTK_DITHERING_SUPPORT = yes
MTK_DMNR_TUNING_AT_MD = no
MTK_DM_APP = no
MTK_DM_ENTRY_DISPLAY = no
MTK_DOCOMO_SUPPORT = no
#yangqing2@lenovo.com 2015-12-10 Dolby Integration begin
MTK_AUDIO_DDPLUS_SUPPORT = yes
MTK_DOLBY_DAP_SUPPORT = yes
#yangqing2@lenovo.com 2015-12-10 Dolby Integration end
#wangwy6 add for aio m version audio
DOLBY_SUPPORT = yes
MTK_DP_FRAMEWORK = yes
MTK_DRM_APP = yes
MTK_DRM_KEY_MNG_SUPPORT = no
MTK_DRM_PLAYREADY_SUPPORT = no
MTK_DSPIRDBG = no
MTK_DTAG_DUAL_APN_SUPPORT = no
MTK_DT_SUPPORT = no
MTK_DUAL_INPUT_CHARGER_SUPPORT = no
#lenovo-sw.lily8.enable dual-mic.2015-10-13
MTK_DUAL_MIC_SUPPORT = yes
#lenovo-sw.lily8.enable dual-mic.2015-10-13
MTK_DVFS_DISABLE_LOW_VOLTAGE_SUPPORT = no
MTK_DX_HDCP_SUPPORT = no
MTK_DYNAMIC_SBP_SUPPORT = no
MTK_EAP_SIM_AKA = yes
MTK_EFUSE_WRITER_SUPPORT = no
MTK_EMMC_DISCARD = no
MTK_EMMC_SUPPORT = yes
MTK_EMMC_SUPPORT_OTP = no
MTK_EMULATOR_SUPPORT = no
MTK_ENABLE_DIVX_DECODER = no
MTK_ENABLE_MD1 = yes
MTK_ENABLE_MD2 = no
MTK_ENABLE_MD3 = no
MTK_ENABLE_MD5 = no
MTK_ENABLE_S263_DECODER = no
MTK_ENABLE_VIDEO_EDITOR = yes
MTK_ENGINEERMODE_APP = yes
MTK_EPDG_SUPPORT = no
MTK_ETHERNET_SUPPORT = no
MTK_ETWS_SUPPORT = no
MTK_EXTERNAL_DONGLE_SUPPORT = no
MTK_EXTERNAL_LDO = no
MTK_EXTERNAL_SIM_SUPPORT = no
MTK_EXTMD_NATIVE_DOWNLOAD_SUPPORT = no
MTK_FACEBEAUTY_SUPPORT = yes
MTK_FACTORY_GAMMA_SUPPORT = no
MTK_FACTORY_MODE_IN_GB2312 = yes
MTK_FACTORY_RESET_PROTECTION_SUPPORT = yes
MTK_FAN5402_SUPPORT = no
MTK_FAN5405_SUPPORT = no
MTK_FASTBOOT_SUPPORT = no
MTK_FAT_ON_NAND = no
MTK_FD_FORCE_REL_SUPPORT = no
MTK_FD_SUPPORT = yes
MTK_FEMTO_CELL_SUPPORT = no
MTK_FENCE_SUPPORT = yes
MTK_FILEMANAGER_APP = yes
MTK_FIRST_MD = 1
#Lenovo-sw lixp5 modify 2015-10-13 begin, for sisley2_M
#MTK_FLIGHT_MODE_POWER_OFF_MD = yes
MTK_FLIGHT_MODE_POWER_OFF_MD = no
#Lenovo-sw lixp5 modify 2015-10-13 end
MTK_FLV_PLAYBACK_SUPPORT = yes
MTK_FMRADIO_APP = yes
MTK_FM_50KHZ_SUPPORT = no
MTK_FM_CHIP = MT6625_FM
MTK_FM_RECORDING_SUPPORT = yes
MTK_FM_RX_AUDIO = FM_DIGITAL_INPUT
MTK_FM_RX_SUPPORT = yes
MTK_FM_SHORT_ANTENNA_SUPPORT = no
MTK_FM_SUPPORT = yes
MTK_FM_TX_AUDIO = FM_DIGITAL_OUTPUT
MTK_FM_TX_SUPPORT = no
MTK_FORCE_CLUSTER1 = no
MTK_FOTA_ENTRY = no
MTK_FOTA_SUPPORT = no
MTK_FSCK_MSDOS_MTK = no
MTK_FSCK_TUNE = no
#Lenovo, miaotao1, disable MTK OTA
#MTK_FW_UPGRADE = yes
MTK_FW_UPGRADE = no
MTK_FW_UPGRADE_APP = no
MTK_GAMELOFT_ASPHALTINJECTION_APP = no
MTK_GAMELOFT_GLLIVE_APP = no
MTK_GAMELOFT_GLL_CN_APP = no
MTK_GAMELOFT_GLL_WW_APP = no
MTK_GAMELOFT_KINGDOMANDLORDS_CN_APP = no
MTK_GAMELOFT_KINGDOMANDLORDS_WW_APP = no
MTK_GAMELOFT_LBC_CN_APP = no
MTK_GAMELOFT_LBC_WW_APP = no
MTK_GAMELOFT_SD_CN_APP = no
MTK_GAMELOFT_SD_WW_APP = no
MTK_GAMELOFT_UNOANDFRIENDS_CN_APP = no
MTK_GAMELOFT_UNOANDFRIENDS_WW_APP = no
MTK_GAMELOFT_WONDERZOO_CN_APP = no
MTK_GAMELOFT_WONDERZOO_WW_APP = no
MTK_GEMINI_3SIM_SUPPORT = no
MTK_GEMINI_4SIM_SUPPORT = no
MTK_GEMINI_ENHANCEMENT = yes
MTK_GMO_RAM_OPTIMIZE = no
MTK_GMO_ROM_OPTIMIZE = no
MTK_GMO_ZYGOTE_ON_DEMAND = no
MTK_GOOGLEOTA_SUPPORT = no
MTK_GPS_CHIP = MTK_GPS_MT6752
MTK_GPS_SUPPORT = yes
MTK_GPT_SCHEME_SUPPORT = yes
MTK_GPU_SUPPORT = yes
MTK_HAC_SUPPORT = yes
MTK_HANDSFREE_DMNR_SUPPORT = yes
MTK_HDMI_HDCP_SUPPORT = no
MTK_HDMI_SUPPORT = no
MTK_HEADER_SUPPORT = yes
MTK_HEADSET_ACTIVE_NOISE_CANCELLATION = no
MTK_HEART_RATE_MONITOR_SUPPORT = no
MTK_HETCOMM_SUPPORT = yes
MTK_HIGH_QUALITY_THUMBNAIL = yes
MTK_HIGH_RESOLUTION_AUDIO_SUPPORT = yes
MTK_HOTKNOT_SUPPORT = no
MTK_HUIYOU_SYJT_APP = no
MTK_HUIYOU_WABAOJINGYING_APP = no
MTK_HW_ENHANCE = no
MTK_HW_KEY_REMAPPING = no
MTK_ICUSB_SUPPORT = no
MTK_IDC_SUPPORT = no
MTK_IMS_SUPPORT = no
# lenovo-sw.lily8.depend on dual-mic,2015-10-13
MTK_INCALL_HANDSFREE_DMNR = yes
MTK_INCALL_NORMAL_DMNR = yes
# lenovo-sw.lily8.depend on dual-mic,2015-10-13
MTK_INCLUDE_MODEM_DB_IN_IMAGE = yes
MTK_INPUTMETHOD_COOTEKIME_TOUCHPAL = yes
MTK_INPUTMETHOD_PINYINIME_APP = no
MTK_INTERNAL = no
MTK_INTERNAL_API_CHECK = no
MTK_INTERNAL_HDMI_SUPPORT = no
MTK_INTERNAL_LANG_SET = no
MTK_INTERNAL_MHL_SUPPORT = no
MTK_INT_MD_SPE_FOR_EXT_MD = no
MTK_IN_HOUSE_TEE_SUPPORT = no
MTK_ION_SUPPORT = yes
MTK_IPOH_SUPPORT = yes
MTK_IPO_MDRST_SUPPORT = no
MTK_IPO_SUPPORT = yes
MTK_IPTV_SUPPORT = no
MTK_IPV6_SUPPORT = yes
MTK_IPV6_TETHER_NDP_MODE = no
MTK_IPV6_TETHER_PD_MODE = no
MTK_IRTX_SUPPORT = no
MTK_ISMS_SUPPORT = no
MTK_JAZZ = no
MTK_JEITA_STANDARD_SUPPORT = no
MTK_K64_SUPPORT = yes
MTK_KERNEL_POWER_OFF_CHARGING = yes
MTK_LAUNCHER_UNREAD_SUPPORT = yes
MTK_LCEEFT_SUPPORT = yes
MTK_LCM_PHYSICAL_ROTATION = 0
MTK_LIVEWALLPAPER_APP = yes
MTK_LOG2SERVER_APP = no
MTK_LOG2SERVER_INTERNAL = no
MTK_LOMO_SUPPORT = yes
MTK_LOW_BAND_TRAN_ANIM = no
MTK_LTE_DC_SUPPORT = no
MTK_LTE_SUPPORT = yes
MTK_M4U_SUPPORT = yes
MTK_MAGICONFERENCE_SUPPORT = no
MTK_MASS_STORAGE = yes
MTK_MATV_ANALOG_SUPPORT = yes
MTK_MATV_SERIAL_IF_SUPPORT = no
MTK_MAV_PLAYBACK_SUPPORT = yes
#Lenovo-sw lixp5 modify 2015-10-13 begin, for sisley2_M
MTK_MD1_SUPPORT=5
MTK_MD2_SUPPORT = 4
MTK_MD3_SUPPORT = 2
MTK_MD5_SUPPORT = 5
#Lenovo-sw lixp5 modify 2015-10-13 end
MTK_MDLOGGER_SUPPORT = yes
MTK_MDM_APP = no
MTK_MDM_FUMO = no
MTK_MDM_LAWMO = no
MTK_MDM_SCOMO = no
MTK_MD_LOW_BAT_SUPPORT = no
MTK_MD_SHUT_DOWN_NT = yes
MTK_MEMORY_COMPRESSION_SUPPORT = no
MTK_MERGE_INTERFACE_SUPPORT = no
MTK_MFV_MPEG4_EXTRA = yes
MTK_MIRAVISION_IMAGE_DC_SUPPORT = no
MTK_MIRAVISION_SETTING_SUPPORT = no
MTK_MLC_NAND_SUPPORT = no
MTK_MMPROFILE_SUPPORT = yes
MTK_MMUMAP_SUPPORT = no
MTK_MOBILE_MANAGEMENT = yes
MTK_MODEM_SUPPORT =
MTK_MPEG_DASH_SUPPORT = no
MTK_MSDC1_NOT_SUPPORT_SDR104 = no
MTK_MT6306_SUPPORT = no
MTK_MT6333_SUPPORT = no
MTK_MT8193_HDCP_SUPPORT = no
MTK_MT8193_HDMI_SUPPORT = no
MTK_MT8193_NFI_SUPPORT = no
MTK_MT8193_SUPPORT = no
MTK_MTKLOGGER_SUPPORT = yes
MTK_MTKPS_PLAYBACK_SUPPORT = no
MTK_MULTIBRIDGE_SUPPORT = no
MTK_MULTICORE_OBSERVER_APP = no
MTK_MULTISIM_RINGTONE_SUPPORT = no
MTK_MULTI_LOG_SD = no
MTK_MULTI_PARTITION_MOUNT_ONLY_SUPPORT = no
MTK_MULTI_STORAGE_SUPPORT = yes
MTK_MULTI_WINDOW_SUPPORT = no
MTK_NAND_PAGE_SIZE = 2K
MTK_NAND_UBIFS_SUPPORT = no
MTK_NATIVE_FENCE_SUPPORT = no
MTK_NEON_SUPPORT = yes
MTK_NETWORK_TYPE_ALWAYS_ON = no
MTK_NETWORK_TYPE_DISPLAY = no
MTK_NEW_COMBO_EMMC_SUPPORT = yes
MTK_NEW_IPTABLES_SUPPORT = yes
MTK_NFC_ADDON_SUPPORT = no
MTK_NFC_GSMA_SUPPORT = no
MTK_NFC_HCE_SUPPORT = no
MTK_NFC_OMAAC_SUPPORT = no
MTK_NFC_OMAAC_VER = 3_2_1
MTK_NFC_SE_NUM = 7
MTK_NFC_SUPPORT = no
MTK_NO_NEED_USB_LED = no
MTK_NO_TRAN_ANIM = no
MTK_NTFS_OPENSOURCE_SUPPORT = no
MTK_NVCONFIG_PARTITION_SUPPORT = no
MTK_NVRAM_SECURITY = no
MTK_OD_SUPPORT = no
MTK_OGM_PLAYBACK_SUPPORT = no
MTK_OMACP_SUPPORT = yes
MTK_OMADRM_SUPPORT = yes
MTK_OMA_DOWNLOAD_SUPPORT = yes
MTK_ONLY_OWNER_SIM_SUPPORT = no
MTK_OPERAMAX_SUPPORT = oupeng
MTK_OVERLAY_ENGINE_SUPPORT = no
MTK_OWNER_SDCARD_ONLY_SUPPORT = no
MTK_PARTITION_TABLE_PLAIN_TEXT = no
MTK_PASSPOINT_R1_SUPPORT = yes
MTK_PASSPOINT_R2_SUPPORT = no
MTK_PCA9575A_SUPPORT = no
MTK_PCB_BATTERY_SENSOR = no
MTK_PERFSERVICE_SUPPORT = yes
#Lenovo-sw jiangtao4 turn off mtk permissioncontrol
MTK_PERMISSION_CONTROL = no
#Lenovo-sw jiangtao4 turn off mtk permissioncontrol
#lenovo-sw fuxm1 2015.10.15 open for persist partition enable begain 
MTK_PERSIST_PARTITION_SUPPORT = no
#lenovo-sw fuxm1 2015.10.15 open for persist partition enable end 
MTK_PHONE_VT_VOICE_ANSWER = no
MTK_PLATFORM = MT6752
MTK_PLATFORM_OPTIMIZE = yes
MTK_PLAYBACK_60FPS_TO_30FPS = no
MTK_PLAYREADY_SUPPORT = no
MTK_PMIC_MT6397 = no
MTK_PM_STATS_SUPPORT = no
MTK_POST_PROCESS_FRAMEWORK_SUPPORT = no
MTK_POWER_EXT_DETECT = no
MTK_PQ_SUPPORT = PQ_HW_VER_2
MTK_PRIVACY_PROTECTION_LOCK = yes
MTK_PRODUCT_INFO_SUPPORT = yes
MTK_PRODUCT_LOCALES = en_US zh_CN zh_TW es_ES pt_BR ru_RU fr_FR de_DE tr_TR vi_VN ms_MY in_ID th_TH it_IT ar_EG hi_IN bn_BD ur_PK fa_IR pt_PT nl_NL el_GR hu_HU tl_PH ro_RO cs_CZ ko_KR km_KH iw_IL my_MM pl_PL es_US bg_BG hr_HR lv_LV lt_LT sk_SK uk_UA de_AT da_DK fi_FI nb_NO sv_SE en_GB hy_AM zh_HK et_EE ja_JP kk_KZ sr_RS sl_SI ca_ES
MTK_PUMP_EXPRESS_SUPPORT = no
MTK_QVGA_LANDSCAPE_SUPPORT = no
MTK_RADIOOFF_POWER_OFF_MD = no
MTK_RAT_BALANCING = no
MTK_RAT_WCDMA_PREFERRED = no
MTK_RAWFS_NAND_SUPPORT = no
MTK_RCSE_SUPPORT = no
MTK_RCS_SUPPORT = no
MTK_REGIONALPHONE_SUPPORT = no
MTK_RELEASE_PACKAGE = rel_customer_basic rel_customer_platform_mt6752
MTK_RESOURCE_OPTIMIZATION =
MTK_RILD_READ_IMSI = yes
MTK_ROTATION_OFFSET_SUPPORT = no
MTK_RSDM_APP = no
MTK_RTP_OVER_RTSP_SUPPORT = yes
MTK_RTSP_BITRATE_ADAPTATION_SUPPORT = no
MTK_RUNTIME_PERMISSION_SUPPORT = no
MTK_SAFEMEDIA_SUPPORT = yes
MTK_SCOMO_ENTRY = no
MTK_SCREEN_OFF_WIFI_OFF = no
MTK_SDIOAUTOK_SUPPORT = no
MTK_SD_SUPPORT = yes
MTK_SEARCH_DB_SUPPORT = yes
MTK_SEC_MODEM_AUTH = no
MTK_SEC_MODEM_ENCODE = no
MTK_SEC_SECRO_AC_SUPPORT = yes
MTK_SEC_VIDEO_PATH_SUPPORT = no
MTK_SEC_WFD_VIDEO_PATH_SUPPORT = no
MTK_SEND_RR_SUPPORT = yes
MTK_SENSOR_HUB_SUPPORT = no
MTK_SENSOR_SUPPORT = yes
MTK_SHARED_SDCARD = yes
MTK_SHARE_MODEM_CURRENT = 2
MTK_SHARE_MODEM_SUPPORT = 2
MTK_SHOW_MSENSOR_TOAST_SUPPORT = no
MTK_SIGNATURE_CUSTOMIZATION = no
MTK_SIGNMODEM_SUPPORT = yes
MTK_SIM1_SOCKET_TYPE = 1
MTK_SIM2_SOCKET_TYPE = 1
#Lenovo-sw lixp5 modify 2015-10-13 begin, for sisley2_M
MTK_SIM_HOT_SWAP = yes
#MTK_SIM_HOT_SWAP_COMMON_SLOT = no
MTK_SIM_HOT_SWAP_COMMON_SLOT = yes
#Lenovo-sw lixp5 modify 2015-10-13 end
MTK_SIM_RECOVERY = yes
MTK_SINA_WEIBO_SUPPORT = no
MTK_SINGLE_3DSHOT_SUPPORT = no
MTK_SINGLE_IMEI = no
MTK_SIP_SUPPORT = yes
MTK_SLC_BUFFER_SUPPORT = no
MTK_SLIDEVIDEO_SUPPORT = yes
MTK_SLOW_MOTION_VIDEO_SUPPORT = yes
MTK_SMARTBOOK_SUPPORT = yes
MTK_SMARTSWITCH_SUPPORT = no
MTK_SMSREG_APP = no
MTK_SMS_NATIONAL_LANGUAGE_SUPPORT = no
MTK_SMS_TURKISH_TABLE_ALWAYS_SUPPORT = yes
MTK_SMT_SUPPORT = no
MTK_SPEAKER_MONITOR_SUPPORT = no
MTK_SPECIAL_FACTORY_RESET = no
MTK_SPECIFIC_SM_CAUSE = no
MTK_SPI_NAND_SUPPORT = no
MTK_SUBTITLE_SUPPORT = no
LENOVO_PIEZO_SPEAKER_SUPPORT = no
MTK_SUPER_DIMMING_SUPPORT = no
MTK_SUPPORT_MJPEG = no
MTK_SUPPORT_TC1_TUNNING = no
MTK_SVLTE_SUPPORT = no
MTK_SWCHR_SUPPORT = no
MTK_SWIP_VORBIS = yes
MTK_SWIP_WMAPRO = no
MTK_SYSTEM_UPDATE_SUPPORT = no
MTK_TABLET_PLATFORM = no
MTK_TABLET_PLUGIN_BUILD = no
MTK_TB_APP_CALL_FORCE_SPEAKER_ON = no
MTK_TB_APP_LANDSCAPE_SUPPORT = no
MTK_TC1_FEATURE = no
MTK_TEE_CCCI_SECURE_SHARE_MEM_SUPPORT = no
MTK_TEE_SUPPORT = no
MTK_TELEPHONY_BOOTUP_MODE_SLOT1 = 0
MTK_TELEPHONY_BOOTUP_MODE_SLOT2 = 1
MTK_TELEPHONY_MODE = 0
MTK_TELSTRA_PDP_RETRY_SUPPORT = no
MTK_TER_SERVICE = no
MTK_TETHERINGIPV6_SUPPORT = yes
MTK_TETHERING_EEM_SUPPORT = no
MTK_THERMAL_PA_VIA_ATCMD = yes
MTK_TINYSYS_SCP_SUPPORT = no
MTK_TINY_UTIL = yes
MTK_TLC_SLC_RATIO = 12
MTK_TLR_SUPPORT = yes
MTK_TOUCH_BOOST = no
MTK_TTY_SUPPORT = yes
MTK_TVOUT_SUPPORT = no
MTK_UART_USB_SWITCH = no
MTK_ULTRA_DIMMING_SUPPORT = no
#Lenovo-sw lixp5 modify 2015-10-13 begin, for sisley2_M
#MTK_UMTS_TDD128_MODE = no
MTK_UMTS_TDD128_MODE= no
#Lenovo-sw lixp5 modify 2015-10-13 end
MTK_USB_AUDIO_SUPPORT = yes
MTK_USB_CBA_SUPPORT = no
MTK_USER_ROOT_SWITCH = no
MTK_USER_SPACE_DEBUG_FW = yes
MTK_USE_ANDROID_MM_DEFAULT_CODE = no
MTK_VIBSPK_SUPPORT = no
MTK_VIDEO_1080P = no
MTK_VIDEO_4KH264_SUPPORT = no
MTK_VIDEO_HEVC_SUPPORT = no
MTK_VIDEO_THUMBNAIL_PLAY_SUPPORT = yes
MTK_VIDEO_VP8ENC_SUPPORT = no
MTK_VILTE_SUPPORT = no
MTK_VLW_APP = yes
MTK_VOICE_CONTACT_SEARCH_SUPPORT = no
MTK_VOICE_INTERFACE_EXTENSION_SUPPORT = no
MTK_VOICE_UI_SUPPORT = no
MTK_VOICE_UNLOCK_SUPPORT = no
MTK_VOICE_UNLOCK_USE_TAB_LIB = no
MTK_VOIP_ENHANCEMENT_SUPPORT = no
#wangwy6 for aio_5m_m bring up 20151111 start
MTK_VOIP_HANDSFREE_DMNR = no
MTK_VOIP_NORMAL_DMNR = no
#wangwy6 for aio_5m_m bring up 20151111 end
MTK_VOLTE_SUPPORT = no
MTK_VOW_SUPPORT = no
MTK_VSS_SUPPORT = no
MTK_VT3G324M_SUPPORT = no
MTK_VZW_CHIPTEST_MODE_SUPPORT = 0
MTK_WAPI_SUPPORT = no
MTK_WAPPUSH_SUPPORT = yes
MTK_WB_SPEECH_SUPPORT = yes
MTK_WEB_NOTIFICATION_SUPPORT = yes
MTK_WEEK_NO = W16.01
MTK_WFC_SUPPORT = no
MTK_WFD_HDCP_TX_SUPPORT = no
MTK_WFD_SINK_SUPPORT = yes
MTK_WFD_SINK_UIBC_SUPPORT = yes
MTK_WFD_SUPPORT = yes
#lenovo-sw.lily8.2015-10-13.add begin
MTK_WIFIWPSP2P_NFC_SUPPORT = no
#lenovo-sw.lily8.2015-10-13.add end
MTK_WIFI_CALLING_RIL_SUPPORT = no
MTK_WIFI_MCC_SUPPORT = yes
MTK_WIFI_P2P_SUPPORT = yes
MTK_WIRELESS_CHARGER_SUPPORT = no
MTK_WLANBT_SINGLEANT = no
MTK_WLAN_CHIP = CONSYS_MT6752
MTK_WLAN_SUPPORT = yes
MTK_WMA_PLAYBACK_SUPPORT = no
MTK_WML_SUPPORT = yes
MTK_WMV_PLAYBACK_SUPPORT = yes
MTK_WORLD_PHONE = no
MTK_WPA2PSK_SUPPORT = no
MTK_WVDRM_L1_SUPPORT = no
MTK_WVDRM_SUPPORT = yes
MTK_YAML_SCATTER_FILE_SUPPORT = yes
MULTI_CH_PLAYBACK_SUPPORT = no
NAND_OTP_SUPPORT = no
NO_INIT_PERMISSION_CHECK = yes
#lenovo-sw.lily8.use external audio pa,2015-10-13
NXP_SMARTPA_SUPPORT = no_nxp
#lenovo-sw.lily8.use external audio pa,2015-10-13
#lenovo-sw,lily8,2014-12-5,AIO-5M for Piezo speaker start
LENOVO_PIEZO_SPEAKER_SUPPORT = no
#lenovo-sw,lily8,2014-12-5,AIO-5M for Piezo speaker end
OP01_COMPATIBLE = no
OPTR_SPEC_SEG_DEF = NONE
PURE_AP_USE_EXTERNAL_MODEM = no
SENSOR_BATCH_SUPPORT = no
SIM_ME_LOCK_MODE = 0
SIM_REFRESH_RESET_BY_MODEM = yes
TARGET_USES_LOGD = true
TELEPHONY_DFOSET = no
TELEPHONY_DFOSET_VALUE = MTK_ENABLE_MD5 MTK_DT_SUPPORT MTK_TELEPHONY_MODE MTK_SHARE_MODEM_SUPPORT MTK_SHARE_MODEM_CURRENT MTK_ENABLE_MD1 MTK_ENABLE_MD2 MTK_FIRST_MD
TRUSTONIC_TEE_SUPPORT = no
USE_FRAUNHOFER_AAC = yes
WIFI_WEP_KEY_ID_SET = no

#CREATE_PROJECT_INFO=2016010712523

#lenovo-sw fuxm1 2015.10.12 add for lenovo recovery begain
LENOVO_RECOVERY_SUPPORT = yes

###### Charging #########################
###lenovo-sw mahj2 modify for charging ic ncp1854 Begin
MTK_NCP1854_SUPPORT = no
LENOVO_POWEROFF_CHARGING_UI = yes
###lenovo-sw mahj2 modify for charging ic ncp1854 End
#lenovo-sw fuxm1 2015.10.12 add for lenovo recovery begain
#lenovo-sw wuwl10 20151207 add for multi index color begin
LENOVO_AIO_PQ_MULTI = no
#lenovo-sw wuwl10 20151207 add for multi index color end
LENOVO_AUDIO_PARA_DYNAMIC_SWITCH = yes
LENOVO_AIO_ROW_PQ_MULTI = yes
